spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    aws:
      region:
        static: ap-northeast-2 # 리전은 아무거나 넣어도 동작하지만, 보통 서울 리전으로 설정
        auto: false
      credentials:
        access-key: ${MINIO_ACCESS} # MinIO 기본 Access Key
        secret-key: ${MINIO_SECRET} # MinIO 기본 Secret Key
      s3:
        endpoint: http://localhost:9000 # 로컬 MinIO 서버 API 주소
        path-style-access-enabled: true # ✅ 매우 중요! MinIO 사용 시 필수 설정

  # 사용자 정의 설정 (업로드할 버킷 이름)
  minio:
    bucket-name: goorm

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.jdbc.core: DEBUG
